[package]
name = "example-01-basics"
version = "0.1.0"
authors = ["Manuel Fuchs <malax@malax.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libcnb = "0.2.0"
